### ISSUE TITLE
User interface design and implementation

### ISSUE THREAD

**Issue by autinerd** [autinerd/csharp-evilcar#2]
The user communicates with the program via a text terminal.

Before the user can enter commands, they need to log-in first (maybe like linux login shell?)
After login succeeds, the user can enter commands to perform things.

A `help` command to list all available commands is required.
A `help <command>` command to get further information is optional, but when the command allows parameters, it should be listed which parameters are taken.
An `exit` command to logout and exit the application is required.
A `logout` command to logout and going back to the login interface is optional.

Maybe the application allows giving the username as a parameter, so the login interface is only asking for the password.

Passwords should not be shown in the console (possible, but difficult)

The user interface only checks the command for correctness and gives the parameters to the inner logic.

There should be a function provided which formats the information given by the inner logic according to information level (Debug, Info, Warning, Error; e.g. only administrators get debug messages) and prints it to the console.
As well as a function which requests further information from the user gives the answer back to the inner logic.
The inner logic is not allowed to access the console by itself.

The inner logic also can give predefined errors to the user interface, which converts them to an error message and print it out.

**Comment by ghost** [comment]
#2 ideas, statements and questions for the command planning

[command planning.txt](https://github.com/autinerd/csharp-evilcar/files/3029283/command.planning.txt)
